// Code generated by protoc-gen-go. DO NOT EDIT.
// source: find_node.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FindNode struct {
	Guid                 []byte   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Version              uint32   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Ip                   []byte   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 uint32   `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	TargetGuid           []byte   `protobuf:"bytes,5,opt,name=targetGuid,proto3" json:"targetGuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindNode) Reset()         { *m = FindNode{} }
func (m *FindNode) String() string { return proto.CompactTextString(m) }
func (*FindNode) ProtoMessage()    {}
func (*FindNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_find_node_72a40a0e42c52694, []int{0}
}
func (m *FindNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindNode.Unmarshal(m, b)
}
func (m *FindNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindNode.Marshal(b, m, deterministic)
}
func (dst *FindNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindNode.Merge(dst, src)
}
func (m *FindNode) XXX_Size() int {
	return xxx_messageInfo_FindNode.Size(m)
}
func (m *FindNode) XXX_DiscardUnknown() {
	xxx_messageInfo_FindNode.DiscardUnknown(m)
}

var xxx_messageInfo_FindNode proto.InternalMessageInfo

func (m *FindNode) GetGuid() []byte {
	if m != nil {
		return m.Guid
	}
	return nil
}

func (m *FindNode) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *FindNode) GetIp() []byte {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *FindNode) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *FindNode) GetTargetGuid() []byte {
	if m != nil {
		return m.TargetGuid
	}
	return nil
}

func init() {
	proto.RegisterType((*FindNode)(nil), "messages.FindNode")
}

func init() { proto.RegisterFile("find_node.proto", fileDescriptor_find_node_72a40a0e42c52694) }

var fileDescriptor_find_node_72a40a0e42c52694 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xcb, 0xcc, 0x4b,
	0x89, 0xcf, 0xcb, 0x4f, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0x56, 0xaa, 0xe1, 0xe2, 0x70, 0xcb, 0xcc, 0x4b, 0xf1, 0xcb, 0x4f,
	0x49, 0x15, 0x12, 0xe2, 0x62, 0x49, 0x2f, 0xcd, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09,
	0x02, 0xb3, 0x85, 0x24, 0xb8, 0xd8, 0xcb, 0x52, 0x8b, 0x8a, 0x33, 0xf3, 0xf3, 0x24, 0x98, 0x14,
	0x18, 0x35, 0x78, 0x83, 0x60, 0x5c, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x02, 0x09, 0x66, 0xb0, 0x5a,
	0xa6, 0xcc, 0x02, 0x90, 0xee, 0x82, 0xfc, 0xa2, 0x12, 0x09, 0x16, 0xb0, 0x32, 0x30, 0x5b, 0x48,
	0x8e, 0x8b, 0xab, 0x24, 0xb1, 0x28, 0x3d, 0xb5, 0xc4, 0x1d, 0x64, 0x2e, 0x2b, 0x58, 0x2d, 0x92,
	0x48, 0x12, 0x1b, 0xd8, 0x39, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xee, 0xd3, 0x5f,
	0xa1, 0x00, 0x00, 0x00,
}
