// Code generated by protoc-gen-go. DO NOT EDIT.
// source: find_node_ack.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FindNodeAck struct {
	Guid                 []byte   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Version              uint32   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Ip                   []byte   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 uint32   `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Nodes                []byte   `protobuf:"bytes,5,opt,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindNodeAck) Reset()         { *m = FindNodeAck{} }
func (m *FindNodeAck) String() string { return proto.CompactTextString(m) }
func (*FindNodeAck) ProtoMessage()    {}
func (*FindNodeAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_find_node_ack_665b032b641e43d0, []int{0}
}
func (m *FindNodeAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindNodeAck.Unmarshal(m, b)
}
func (m *FindNodeAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindNodeAck.Marshal(b, m, deterministic)
}
func (dst *FindNodeAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindNodeAck.Merge(dst, src)
}
func (m *FindNodeAck) XXX_Size() int {
	return xxx_messageInfo_FindNodeAck.Size(m)
}
func (m *FindNodeAck) XXX_DiscardUnknown() {
	xxx_messageInfo_FindNodeAck.DiscardUnknown(m)
}

var xxx_messageInfo_FindNodeAck proto.InternalMessageInfo

func (m *FindNodeAck) GetGuid() []byte {
	if m != nil {
		return m.Guid
	}
	return nil
}

func (m *FindNodeAck) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *FindNodeAck) GetIp() []byte {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *FindNodeAck) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *FindNodeAck) GetNodes() []byte {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*FindNodeAck)(nil), "messages.FindNodeAck")
}

func init() { proto.RegisterFile("find_node_ack.proto", fileDescriptor_find_node_ack_665b032b641e43d0) }

var fileDescriptor_find_node_ack_665b032b641e43d0 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xcb, 0xcc, 0x4b,
	0x89, 0xcf, 0xcb, 0x4f, 0x49, 0x8d, 0x4f, 0x4c, 0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0xc8, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0x56, 0x2a, 0xe5, 0xe2, 0x76, 0xcb, 0xcc,
	0x4b, 0xf1, 0xcb, 0x4f, 0x49, 0x75, 0x4c, 0xce, 0x16, 0x12, 0xe2, 0x62, 0x49, 0x2f, 0xcd, 0x4c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0xb3, 0x85, 0x24, 0xb8, 0xd8, 0xcb, 0x52, 0x8b,
	0x8a, 0x33, 0xf3, 0xf3, 0x24, 0x98, 0x14, 0x18, 0x35, 0x78, 0x83, 0x60, 0x5c, 0x21, 0x3e, 0x2e,
	0xa6, 0xcc, 0x02, 0x09, 0x66, 0xb0, 0x5a, 0xa6, 0xcc, 0x02, 0x90, 0xee, 0x82, 0xfc, 0xa2, 0x12,
	0x09, 0x16, 0xb0, 0x32, 0x30, 0x5b, 0x48, 0x84, 0x8b, 0x15, 0x64, 0x79, 0xb1, 0x04, 0x2b, 0x58,
	0x19, 0x84, 0x93, 0xc4, 0x06, 0x76, 0x87, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x20, 0x2c, 0x40,
	0xc0, 0x9e, 0x00, 0x00, 0x00,
}
