// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello_tcp.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloTCP struct {
	Guid                 []byte   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Node                 []byte   `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloTCP) Reset()         { *m = HelloTCP{} }
func (m *HelloTCP) String() string { return proto.CompactTextString(m) }
func (*HelloTCP) ProtoMessage()    {}
func (*HelloTCP) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_tcp_57ac8b65d95434de, []int{0}
}
func (m *HelloTCP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloTCP.Unmarshal(m, b)
}
func (m *HelloTCP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloTCP.Marshal(b, m, deterministic)
}
func (dst *HelloTCP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloTCP.Merge(dst, src)
}
func (m *HelloTCP) XXX_Size() int {
	return xxx_messageInfo_HelloTCP.Size(m)
}
func (m *HelloTCP) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloTCP.DiscardUnknown(m)
}

var xxx_messageInfo_HelloTCP proto.InternalMessageInfo

func (m *HelloTCP) GetGuid() []byte {
	if m != nil {
		return m.Guid
	}
	return nil
}

func (m *HelloTCP) GetNode() []byte {
	if m != nil {
		return m.Node
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloTCP)(nil), "messages.HelloTCP")
}

func init() { proto.RegisterFile("hello_tcp.proto", fileDescriptor_hello_tcp_57ac8b65d95434de) }

var fileDescriptor_hello_tcp_57ac8b65d95434de = []byte{
	// 94 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x48, 0xcd, 0xc9,
	0xc9, 0x8f, 0x2f, 0x49, 0x2e, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0x56, 0x32, 0xe2, 0xe2, 0xf0, 0x00, 0x49, 0x86, 0x38, 0x07, 0x08,
	0x09, 0x71, 0xb1, 0xa4, 0x97, 0x66, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x81, 0xd9,
	0x20, 0xb1, 0xbc, 0xfc, 0x94, 0x54, 0x09, 0x26, 0x88, 0x18, 0x88, 0x9d, 0xc4, 0x06, 0x36, 0xc4,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xde, 0xbe, 0xc2, 0xda, 0x57, 0x00, 0x00, 0x00,
}
