// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request_height.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestHeight struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Version              uint32   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeight) Reset()         { *m = RequestHeight{} }
func (m *RequestHeight) String() string { return proto.CompactTextString(m) }
func (*RequestHeight) ProtoMessage()    {}
func (*RequestHeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_height_785d0ac221b78ff3, []int{0}
}
func (m *RequestHeight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeight.Unmarshal(m, b)
}
func (m *RequestHeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeight.Marshal(b, m, deterministic)
}
func (dst *RequestHeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeight.Merge(dst, src)
}
func (m *RequestHeight) XXX_Size() int {
	return xxx_messageInfo_RequestHeight.Size(m)
}
func (m *RequestHeight) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeight.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeight proto.InternalMessageInfo

func (m *RequestHeight) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *RequestHeight) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestHeight)(nil), "messages.RequestHeight")
}

func init() {
	proto.RegisterFile("request_height.proto", fileDescriptor_request_height_785d0ac221b78ff3)
}

var fileDescriptor_request_height_785d0ac221b78ff3 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x89, 0xcf, 0x48, 0xcd, 0x4c, 0xcf, 0x28, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0xc8, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0x56, 0x72, 0xe4, 0xe2, 0x0d, 0x82,
	0xa8, 0xf0, 0x00, 0x2b, 0x10, 0x12, 0xe3, 0x62, 0x83, 0x28, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60,
	0x09, 0x82, 0xf2, 0x84, 0x24, 0xb8, 0xd8, 0xcb, 0x52, 0x8b, 0x8a, 0x33, 0xf3, 0xf3, 0x24, 0x98,
	0x14, 0x18, 0x35, 0x78, 0x83, 0x60, 0xdc, 0x24, 0x36, 0xb0, 0x99, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x33, 0x51, 0x97, 0xcb, 0x6b, 0x00, 0x00, 0x00,
}
